#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

"""Add first last seen

Revision ID: 2d7ae226fd06
Revises: 17e26c339754
Create Date: 2025-01-21 10:43:50.857641

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d7ae226fd06'
down_revision = '17e26c339754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_risk', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('first_seen', sa.DateTime(), nullable=False)
        )
        batch_op.add_column(
            sa.Column('last_seen', sa.DateTime(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_risk', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('first_seen')

    # ### end Alembic commands ###
